name        : jml-java-7          # name of the package
version     : 1.7-2       # version of the package
kind        : spec                     # one of tool or spec(s)
description : JML Specifications for the Java Language, Version 7
extends     : jml-java-6              
author:
  - name: John L. Singleton
    email: jsinglet@gmail.com

